user(login): create root to login as user and logout
BeautifulStack/php-back pull request #16
Opened 2021-04-26 20:10 UTC by AtoLrn

C'est pas fait de la manière la plus belle mais y'a des trucs casses tête à faire,
En gros je suis oubligé de passer les where comme ça, car sinon faut faire un truc beaucoup plus complexe et je me sens pas de le faire maintenant

Sinon, tout fonctionne, quand J'aurai fait les modifs voulu et merge je pourrai faire la gestion du login en front

2021-04-26 20:12 UTC, AtoLrn commented
Et du coup je ne sais pas ou placer le grand bout de code dans le router, je pense que il pourra être utilisé autre part

2021-04-26 20:19 UTC, AtoLrn commented
Enfaite C'est bon !

2021-04-27 11:52 UTC, sven-eliasen commented on src/Crud/CrudClass/CrudClass.php
> +        $args = $this->check_attributes([]);
malynx le lynx

2021-04-27 12:55 UTC, sven-eliasen requested changes
Pense à retirer les `//var_dump()` quand t'as fini.

Sinon pour les `where`:
- Il prends en argument un dict avec `<nom de colonne> => <valeur>`
- Check tout les nom de colonne avec `check_attributes_update`
- puis construit la query en concatenent **que** les nom de colonne
- et enfin `prepare()` la requete avec les valeurs

Sinon je pense que tu peux mettre login en tant que méthode static de `HandlerUser`

PS: Mdr t'as programmé ton `Login` comme si c'était un component

2021-04-27 17:35 UTC, AtoLrn commented
Oui pour le where j'ai pensé à le faire comme ça, et pour le user, je trouve ça dommage de devoir instancier la classe User juste pour le login si on a déjà une variable de session qui le fait,
mais en vrai je vois pas le problème de faire comme ça pour le login :(

2021-04-27 18:03 UTC, sven-eliasen commented
> je trouve ça dommage de devoir instancier la classe User
C'est pour ça que j'ai dit méthode static

2021-04-27 18:11 UTC, AtoLrn commented
Ah bah oui du coup je comprends mieux, j'avais sauté le mot static

2021-04-28 11:41 UTC, sven-eliasen requested changes
Mdr je vais être casse couille mais je voulais que tu mettes encrypt() et login() dans HandlerUser, dans User.php on met que les interactions avec la bdd

2021-04-28 19:07 UTC, AtoLrn commented
Et maintenant ? ;(

2021-04-29 10:59 UTC, sven-eliasen approved these changes
Allez, je t'ai bien fait chier voici t'as récompense : \(0^◇^0)/

2021-04-30 20:01 UTC, lealaroze approved these changes

2021-04-30 20:03 UTC, merged